name: Wails build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: chatgpt, platform: linux/amd64, os: ubuntu-latest},
          {name: chatgpt, platform: windows/amd64, os: windows-latest},
          {name: chatgpt, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
      runs-on: macos-latest
      steps:
        # Checkout code
        - uses: actions/checkout@v3
          with:
            submodules: recursive
        - uses: dAppServer/wails-build-action@v2
          with:
            build-name: cohort-wails
            build-platform: darwin/universal
            wails-build-webview2: "embed"
            wails-version: "v2.3.1"
            go-version: ^1.18
            sign: "false"