name: Wails build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: GPT聚合版, platform: linux/amd64, os: ubuntu-latest},
          {name: GPT聚合版, platform: windows/amd64, os: windows-latest},
          {name: GPT聚合版, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
